version: 1
"""
Logging configuration
"""
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log  # This will be updated dynamically
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log  # This will be updated dynamically
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  audit_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/audit.log  # This will be updated dynamically
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  src:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

  src.api:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  src.security.auth:
    level: INFO
    handlers: [console, file, audit_file]
    propagate: false

  src.pipeline:
    level: DEBUG
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
  propagate: false